/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CadastroJAVAFx;

/**
 *
 * @author jefferson_B
 */
public class ConsultaProfissional extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarProfissional
     */
    
    public ConsultaProfissional() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeProfissional = new javax.swing.JLabel();
        lblConsultaNomeProfissional = new javax.swing.JTextField();
        btnPesquisarProfissional = new javax.swing.JButton();
        btnNovoProfissional = new javax.swing.JButton();
        btnAlterarProfissional = new javax.swing.JButton();
        btnExcluirProfissional = new javax.swing.JButton();
        btnCancelarProfissional = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProfissional = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Profissional");
        setPreferredSize(new java.awt.Dimension(600, 300));

        nomeProfissional.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomeProfissional.setForeground(new java.awt.Color(204, 0, 0));
        nomeProfissional.setText("NOME:");

        lblConsultaNomeProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblConsultaNomeProfissionalActionPerformed(evt);
            }
        });

        btnPesquisarProfissional.setText("Pesquisar");

        btnNovoProfissional.setText("Novo");

        btnAlterarProfissional.setText("Alterar");

        btnExcluirProfissional.setText("Excluir");

        btnCancelarProfissional.setText("Cancelar");

        TableProfissional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "DDD", "Telefone", "E-mail", "CPF", "RG", "Nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableProfissional);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(nomeProfissional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblConsultaNomeProfissional))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisarProfissional)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovoProfissional)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarProfissional)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirProfissional)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarProfissional)
                        .addGap(0, 153, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsultaNomeProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeProfissional))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarProfissional)
                    .addComponent(btnNovoProfissional)
                    .addComponent(btnAlterarProfissional)
                    .addComponent(btnExcluirProfissional)
                    .addComponent(btnCancelarProfissional))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblConsultaNomeProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblConsultaNomeProfissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsultaNomeProfissionalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableProfissional;
    private javax.swing.JButton btnAlterarProfissional;
    private javax.swing.JButton btnCancelarProfissional;
    private javax.swing.JButton btnExcluirProfissional;
    private javax.swing.JButton btnNovoProfissional;
    private javax.swing.JButton btnPesquisarProfissional;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblConsultaNomeProfissional;
    private javax.swing.JLabel nomeProfissional;
    // End of variables declaration//GEN-END:variables
}
