package CadastroJAVAFx;

/**
 *
 * @author jefferson_B
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form home_screen
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        smClientes = new javax.swing.JMenuItem();
        smProfissionais = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenu();
        smDicasRapidas = new javax.swing.JMenuItem();
        smFaleConosco = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPrincipal.setPreferredSize(new java.awt.Dimension(600, 300));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mCadastro.setText("Cadastro");
        mCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastroActionPerformed(evt);
            }
        });

        smClientes.setText("Clientes");
        smClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smClientesActionPerformed(evt);
            }
        });
        mCadastro.add(smClientes);

        smProfissionais.setText("Profissionais");
        smProfissionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smProfissionaisActionPerformed(evt);
            }
        });
        mCadastro.add(smProfissionais);

        jMenuBar1.add(mCadastro);

        mAjuda.setText("Ajuda");

        smDicasRapidas.setText("Dicas Rápidas");
        smDicasRapidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smDicasRapidasActionPerformed(evt);
            }
        });
        mAjuda.add(smDicasRapidas);

        smFaleConosco.setText("Fale Conosco");
        smFaleConosco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smFaleConoscoActionPerformed(evt);
            }
        });
        mAjuda.add(smFaleConosco);

        jMenuBar1.add(mAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smFaleConoscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smFaleConoscoActionPerformed
        FaleConosco faleConosco = new FaleConosco();
        this.jdpPrincipal.add(faleConosco);
        faleConosco.setVisible(true);
    }//GEN-LAST:event_smFaleConoscoActionPerformed

    private void smClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smClientesActionPerformed
        ConsultaCliente consultaCliente = new ConsultaCliente();
        this.jdpPrincipal.add(consultaCliente);
        consultaCliente.setVisible(true);
    }//GEN-LAST:event_smClientesActionPerformed

    private void smProfissionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smProfissionaisActionPerformed
        ConsultaProfissional consultaProfissional = new ConsultaProfissional();
        this.jdpPrincipal.add(consultaProfissional);
        consultaProfissional.setVisible(true);
    }//GEN-LAST:event_smProfissionaisActionPerformed

    private void smDicasRapidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smDicasRapidasActionPerformed
        DicasRapidas dicasRapidas = new DicasRapidas();
        this.jdpPrincipal.add(dicasRapidas);
        dicasRapidas.setVisible(true);
    }//GEN-LAST:event_smDicasRapidasActionPerformed

    private void mCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenuItem smClientes;
    private javax.swing.JMenuItem smDicasRapidas;
    private javax.swing.JMenuItem smFaleConosco;
    private javax.swing.JMenuItem smProfissionais;
    // End of variables declaration//GEN-END:variables
}
